Update btenforce

diff --git a/btenforce b/btenforce
--- a/btenforce
+++ b/btenforce
@@ -24,8 +24,7 @@
 ##            - btenforce is now a combination of the Bluetooth utility plus
 ##              other functions such as Safari control and login item control. 
 ##              See the config file for more information.
-##            - The included version of blueutil is version 9 due to some irregularities 
-##              with newer versions on macOS 26.
+##            - The included version of blueutil is version 9 due to some irregularities with newer versions on macOS 26.
 ##            - Removed ANSI color coding from log messages.
 ##            - Added logging to configuration function.
 ##            - Added comment indicating that the script is running as a standard user.
@@ -40,16 +39,10 @@
 ##            - Added check for blueutil and then copy it from /usr/local/share/btenforce/blueutil if not found in /usr/local/bin.
 ##            - Added MDM_TYPE variable for clarity in config file.
 ##            - Added version to the log header in the config file for easy identification.
-##            - Refined configuration function for usability and convenience. It will
-##              now check for configuration errors in the config file and report
-##              them to the user.
-##            - Added parameters to postinstall script for Jamf Pro MDM and 
-##              Mosyle MDM. See the notes in the postinstall script for more
-##              information.
-##            - Enhanced time entry and validation for the configuration 
-##              function.
-##            - Added warning when configuring Safari function with osascript
-##              method on macOS.
+##            - Refined configuration function for usability and convenience. It will now check for configuration errors in the config file and report them to the user.
+##            - Added parameters to postinstall script for Jamf Pro MDM and Mosyle MDM. See the notes in the postinstall script for more information.
+##            - Enhanced time entry and validation for the configuration function.
+##            - Added warning when configuring Safari function with osascript method on macOS.
 ##            - Added the method used to configure btenforce to the config file along with the time and date of the configuration.
 ##            - Reduced unessential noise from logs.
 ##            - Added check for BTENFORCE_ACTIVE in config file and exit if not found.
@@ -57,10 +50,8 @@
 ##            - Changed logic to continue if no user is logged on, then skip the controls and log the exit code.
 ##            - Added trap for INT and TERM signals to log the exit code and exit.
 ##            - Added trap for ERR signal to log the error message and exit.
-##            - Reduced unessential noise from logs when school is not in session by adding a flag file to
-##              prevent the script from logging on every execution.
-##            - Modified the shebang from /bin/zsh to /bin/bash for compatibility in the post-install script.
-##              since that will be most likely executed by an MDM and if Mosyle, must be Bash.
+##            - Reduced unessential noise from logs when school is not in session by adding a flag file to prevent the script from logging on every execution.
+##            - Modified the shebang from /bin/zsh to /bin/bash for compatibility in the post-install script since that will be most likely executed by an MDM and if Mosyle, must be Bash.
 ##
 ## Author: Keith Myers | keith.myers@i-techsupport.com
 ##
@@ -103,6 +94,7 @@ SCRIPT_PATH="${0:A}"
 EXIT_CODE="0"
 ACTIVE_USER="false"
 NW_FLAG="/Library/Application Support/i-Tech/btenforce.nw"
+OVERRIDE_FLAG="/Library/Application Support/i-Tech/btenforce.ov"
 REPO="https://github.com/i-TechSupport-orlando/btenforce"
 
 # Application configuration file.
@@ -255,7 +247,7 @@ configure_btenforce() {
 
     echo -e "Press ENTER for the default value shown in square brackets or make a selection:\n"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Enable/disable the daemon as a whole.
     if read -s -k 1 -t 600 "BTENFORCE_ACTIVE?[${option_number}/${total_options}] Enable btenforce? ([${ORANGE}Y${NC}]/N): "; then
         if [[ "$BTENFORCE_ACTIVE" == "Y" || "$BTENFORCE_ACTIVE" == "y" ]]; then
@@ -274,7 +266,7 @@ configure_btenforce() {
     fi
 
     echo "-------------------------------"
-    ((option_number++))
+    (( option_number += 1 ))
     # Safari option. 'enforce' or 'allow'
     if read -s -k 1 -t 600 "SAFARI_CONTROL?[${option_number}/${total_options}] Enforce Safari restrictions? (force students to use Chrome, for example) (Y/[${ORANGE}N${NC}]): "; then
         if [[ "$SAFARI_CONTROL" == "Y" || "$SAFARI_CONTROL" == "y" ]]; then
@@ -294,7 +286,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Bluetooth option. 'enforce' or 'allow'
     if read -s -k 1 -t 600 "BLUETOOTH_CONTROL?[${option_number}/${total_options}] Enforce Bluetooth restrictions? (students will not be able to turn off Bluetooth) (Y/[${ORANGE}N${NC}]): "; then
         if [[ "$BLUETOOTH_CONTROL" == "Y" || "$BLUETOOTH_CONTROL" == "y" ]]; then
@@ -314,7 +306,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Login item controls. 'enforce' or 'allow'
     if read -s -k 1 -t 600 "LOGIN_ITEM_CONTROL?[${option_number}/${total_options}] Enforce login item controls? (restrict students from adding or removing login items) (Y/[${ORANGE}N${NC}]): "; then
         if [[ "$LOGIN_ITEM_CONTROL" == "Y" || "$LOGIN_ITEM_CONTROL" == "y" ]]; then
@@ -334,7 +326,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Override time constraints. 'No' means student control enabled on nights/weekends.
     if read -s -k 1 -t 600 "TIME_CONSTRAINT_OVERRIDE?[${option_number}/${total_options}] Override the time constraints and enforce btenforce options 24x7? (Y/[${ORANGE}N${NC}]): "; then
         if [[ "$TIME_CONSTRAINT_OVERRIDE" == "Y" || "$TIME_CONSTRAINT_OVERRIDE" == "y" ]]; then
@@ -379,7 +371,7 @@ configure_btenforce() {
 
     # echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Safari blocking option. 'osascript', 'pgrep'
     if read -s -k 1 -t 600 "SAFARI_CONTROL_METHOD?[${option_number}/${total_options}] Enter Safari blocking method: (Osascript/[${ORANGE}P${NC}]grep): "; then
         if [[ "$SAFARI_CONTROL_METHOD" == "O" || "$SAFARI_CONTROL_METHOD" == "o" ]]; then
@@ -400,7 +392,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # School start time in 24-hour clock. Hour only.
     if read -t 600 "BTENFORCE_START_TIME?[${option_number}/${total_options}] Enter school start time (5 characters as in 07:00 or press ENTER for [${ORANGE}07:00${NC}]): "; then
         if [[ -z "$BTENFORCE_START_TIME" ]]; then
@@ -424,7 +416,7 @@ configure_btenforce() {
 
     echo "-------------------------------"  
 
-    ((option_number++))
+    (( option_number += 1 ))
     # School stop time in 24-hour clock. Hour only.
     if read -t 600 "BTENFORCE_STOP_TIME?[${option_number}/${total_options}] Enter school stop time (5 characters as in 15:00 or press ENTER for [${ORANGE}15:00${NC}]): "; then
         if [[ -z "$BTENFORCE_STOP_TIME" ]]; then
@@ -447,7 +439,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Set the retention period for log files. Default is 180 days.
     if read -t 600 "LOG_RETENTION?[${option_number}/${total_options}] Enter log retention period in days from 7-1095 (Press enter for [${ORANGE}180${NC}]): "; then
         if [[ -z "$LOG_RETENTION" ]]; then
@@ -466,7 +458,7 @@ configure_btenforce() {
 
     echo "-------------------------------"
 
-    ((option_number++))
+    (( option_number += 1 ))
     # Log file path. Use a new variable so that the log currently running isn't affected.
     local new_log_path=""
     if read -t 600 "new_log_path?[${option_number}/${total_options}] Enter log file path (press enter for [${ORANGE}${BTENFORCE_LOG_FILE}${NC}]): "; then
@@ -630,41 +622,46 @@ prune_logs () {
 
 # Install the LaunchDaemon if it doesn't exist.
 install_daemon () {
+    local daemon_url
+    daemon_url="https://raw.githubusercontent.com/i-TechSupport-orlando/btenforce/refs/heads/main/btenforce"
+
     if [[ ! -f "$PLIST" ]]; then
-        if [[ -f "$PLIST_SOURCE" ]]; then
-            cp "$PLIST_SOURCE" "$PLIST"
-            chown root:wheel "$PLIST"
-            chmod 644 "$PLIST"
-        else
-            append_log "Error: LaunchDaemon source file not found: ${PLIST_SOURCE}"
-            return 1
-        fi
-
-        daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )
-
-        # Already running. Unload and reload.
-        if [[ -n "$daemon_status" ]]; then
-            launchctl bootout system/com.itech.btenforce
-            sleep 1
-            launchctl bootstrap system "$PLIST"
-            sleep 1
-            daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )
-            if [[ -n "$daemon_status" ]]; then
-                append_log "LaunchDaemon installed and reloaded."
-                return 0
+        if curl -fsSL "$daemon_url" -o "$PLIST"; then
+            if chown root:wheel "$PLIST"; then
+                append_log "Ownership of daemon changed to root:wheel."
             else
-                append_log "The daemon failed to reload."
+                append_log "Failed to change ownership of daemon to root:wheel."
+                return 1
+            fi
+
+            if chmod 644 "$PLIST"; then
+                append_log "Permissions of daemon set to 644."
+            else
+                append_log "Failed to set permissions of daemon to 644."
                 return 1
             fi
         else
-            append_log "Installing new LaunchDaemon..."
+            append_log "Error: Could not download daemon from GitHub: ${daemon_url}"
+            append_log "Download manually from ${REPO}"
+            return 1
+        fi
 
+        append_log "Installing new LaunchDaemon..."
+
+        launchctl bootstrap system "$PLIST"
+
+        sleep 1
+
+        daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )
+
+        if [[ -n "$daemon_status" ]]; then
+            append_log "LaunchDaemon installed and loaded."
+            return 0
+        else
+            append_log "The daemon failed to start. Attempting to restart..."
             launchctl bootstrap system "$PLIST"
-
-            sleep 1
-
+            sleep 2
             daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )
-
             if [[ -n "$daemon_status" ]]; then
                 append_log "LaunchDaemon installed and loaded."
                 return 0
@@ -757,8 +754,13 @@ return "false"
 # Check whether the current date/time is during regular school hours.
 during_school_hours () {
     
-    if [[ "$BTENFORCE_DEBUG_MODE" == "true" || "$TIME_CONSTRAINT_OVERRIDE" == "true" ]]; then
-        append_log "School hours are not considered due to debug mode or time constraint override set to true."
+    if [[ ("$BTENFORCE_DEBUG_MODE" == "true" || "$TIME_CONSTRAINT_OVERRIDE" == "true") && ! -f "$OVERRIDE_FLAG" ]]; then
+        touch "$OVERRIDE_FLAG"
+        append_log "School hours are not being considered due to debug mode or time constraint override set to true. Created override flag."
+        return 0
+    elif [[ ("$BTENFORCE_DEBUG_MODE" == "false" || "$TIME_CONSTRAINT_OVERRIDE" == "false") && -f "$OVERRIDE_FLAG" ]]; then
+        rm -f "$OVERRIDE_FLAG"
+        append_log "School hours are now being considered. Removed override flag."
         return 0
     fi
 
@@ -787,7 +789,7 @@ during_school_hours () {
         fi
     fi
 
-    # Create flag file so it doesn't log every minute when school is not in session.
+    # Create flag file so it doesn't log on every execution when school is not in session.
     if [[ ! -f "$NW_FLAG" ]]; then
         append_log "Not during school hours. Creating flag file."
         touch "$NW_FLAG"
@@ -806,8 +808,7 @@ check_login_items () {
         
     if [[ "$login_item_count" -gt 0 ]]; then
         runAsUser osascript -e 'tell application "System Events" to delete login items'
-        login_item_status="Removed ${login_item_count} login items for ${loggedInUser}"
-        append_log "$login_item_status"
+        append_log "Removed ${login_item_count} login items for ${loggedInUser}"
     fi
 }
 
@@ -838,7 +839,7 @@ trapint() {
 
 trap "finished" EXIT
 trap "trapint" INT TERM
-trap 'append_log "Error on line $LINENO: $(sed -n ${LINENO}p \"$0\")"' ERR
+trap '[[ -f "$0" ]] && append_log "Error on line $LINENO: $(sed -n ${LINENO}p \"$0\")" || append_log "Error in $0 on line $LINENO"' ERR
 
 # Process arguments if there are any.
 if [[ "$#" -ge 1 ]]; then
@@ -875,14 +876,13 @@ fi
 
 if [[ "$BTENFORCE_DEBUG_MODE" == "true" ]]; then
     set -x
-    append_log "Debug mode has been enabled. For support, please contact i-Tech at (407) 265-2000."
-    append_log "support@i-techsupport.com  https://www.i-techsupport.com"
+    append_log "Debug mode has been enabled."
     debug_info
 else
     set +x
 fi
 
-# Check if the daemon is active.
+# Check if the daemon is enabled.
 if [[ "$BTENFORCE_ACTIVE" == "true" ]]; then
 
     # Check the day and time, then perform actions if the current time is within the specified period.
@@ -890,15 +890,12 @@ if [[ "$BTENFORCE_ACTIVE" == "true" ]]; then
         
         # Install the daemon if missing, then check each item.
         if [[ ! -f "$PLIST" ]]; then
-            append_log "Daemon not found. Reinstall btenforce."
-            exit 113
+            if ! install_daemon; then
+                exit 113
+            fi
         fi
 
         if [[ "$ACTIVE_USER" == "true" ]]; then
-
-            if [[ "$LOGIN_ITEM_CONTROL" == "enforce" ]]; then
-                check_login_items
-            fi   
         
             if [[ "$BLUETOOTH_CONTROL" == "enforce" ]]; then
                 check_bluetooth
