Bug fixes

diff --git a/btenforce b/btenforce
--- a/btenforce
+++ b/btenforce
@@ -115,6 +115,7 @@ REPO="https://github.com/i-TechSupport-orlando/btenforce"
 # Application configuration file.
 BTENFORCE_CONFIG="/Library/Application Support/i-Tech/btenforce.env"
 BTENFORCE_LOG_FILE="/var/log/btenforce.log"
+BLUEUTIL="/usr/local/bin/blueutil"
 TODAY=$( date +%Y-%m-%d )
 PLIST="/Library/LaunchDaemons/com.itech.btenforce.plist"
 
@@ -178,6 +179,8 @@ fi
 
 # Function to display debug information.
 debug_info() {
+    local files_to_check log_size current_bt_status current_interval
+    
     append_log "BTENFORCE_CONFIG:         ${BTENFORCE_CONFIG}"
     append_log "BTENFORCE_LOG_FILE:       ${BTENFORCE_LOG_FILE}"
     append_log "BTENFORCE_ACTIVE:         ${BTENFORCE_ACTIVE}"
@@ -190,8 +193,12 @@ debug_info() {
     append_log "loggedInUser:             ${loggedInUser}"
     append_log "User ID:                  ${uid}"
     append_log "TIME_CONSTRAINT_OVERRIDE: ${TIME_CONSTRAINT_OVERRIDE}"
-    
-    local files_to_check log_size current_bt_status
+
+    # Get current interval
+    current_interval=$( plutil -extract "StartInterval" raw "$PLIST" 2>/dev/null )
+    append_log "Current interval:         ${current_interval} (from plist)"
+    append_log "Configured interval:      ${BTENFORCE_INTERVAL} (from config file)"
+
     files_to_check=("$NIGHTWKN_FLAG" "$INACTIVE_FLAG" "$OVERRIDE_FLAG" "$PLIST" "$BTENFORCE_CONFIG" "$BTENFORCE_LOG_FILE" "$NO_LOGIN_FLAG" "/usr/local/bin/blueutil")
     
     for file in "${files_to_check[@]}"; do
@@ -266,7 +273,7 @@ configure_btenforce() {
     failed_items=0
 
     clear
-    local total_options=10
+    local total_options=11
     local option_number=0
 
     TERM=xterm-256color
@@ -326,6 +333,42 @@ configure_btenforce() {
     fi
 
     echo "-------------------------------"
+
+    (( option_number += 1 ))
+	# Regex for between 1 and 3600.
+	interval_regex='^([1-9]|[1-9][0-9]{1,2}|[1-2][0-9]{3}|3[0-5][0-9]{2}|3600)$'
+	if read -t 600 "BTENFORCE_INTERVAL?[${option_number}/${total_options}] Enter the number of seconds between 1 and 3600 to wait between checks [${ORANGE}5${NC}]: "; then
+		if [[ -z "$BTENFORCE_INTERVAL" ]]; then
+			BTENFORCE_INTERVAL="5"
+			echo -e "${GREEN}Using default interval ${BTENFORCE_INTERVAL}.${NC}"
+		else
+			# Check against regex.
+			if [[ "$BTENFORCE_INTERVAL" =~ "$interval_regex" ]]; then
+				if [[ "$BTENFORCE_INTERVAL" -ge 600 ]]; then
+					echo -e "${YELLOW}The interval is set to ten minutes or longer. btenforce may not be effective. A maximum of 10 seconds is recommended with 5 being optimal.${NC}"
+				elif [[ "$BTENFORCE_INTERVAL" -le 4 ]]; then
+					echo -e "${YELLOW}An interval of less than 5 seconds may be too short! 5 is optimal.${NC}"
+				elif [[ "$BTENFORCE_INTERVAL" -ge 60 ]]; then
+					echo -e "${YELLOW}An interval of a full minute or longer may be too long! 5 is optimal."
+				fi
+				echo -e "${GREEN}Interval set to: ${BTENFORCE_INTERVAL}.${NC}"
+			else
+				echo -e "${RED}Invalid value entered: ${BTENFORCE_INTERVAL} - Defaulting to 5.${NC}"
+			fi
+		fi
+	else
+		echo -e "${YELLOW}Timeout has expired. Defaulting to: 5.${NC}"
+        BTENFORCE_INTERVAL="5"
+	fi
+
+    # Modify the plist and restart the daemon if the Interval was changed from its default.
+    if [[ "$BTENFORCE_INTERVAL" != 5 ]]; then
+        append_log "\n${GREEN}Resetting the interval...${NC}"
+        set_btenforce_interval
+    fi
+
+    echo "-------------------------------"
+
     (( option_number += 1 ))
     # Safari option. 'enforce' or 'allow'
     if read -s -k 1 -t 600 "SAFARI_CONTROL?[${option_number}/${total_options}] Enforce Safari restrictions? (force students to use Chrome, for example) (Y/[${ORANGE}N${NC}]): "; then
@@ -550,6 +593,7 @@ configure_btenforce() {
         fi
     fi
 
+
     append_log "\n${GREEN}Writing configuration file: ${BTENFORCE_CONFIG}\n${NC}"
     cat << EOF > "$BTENFORCE_CONFIG"
 
@@ -572,6 +616,9 @@ configure_btenforce() {
 
 # Enable/disable the daemon (true/false).
 BTENFORCE_ACTIVE="$BTENFORCE_ACTIVE"
+
+# Interval between checks in seconds (1-3600).
+BTENFORCE_INTERVAL="$BTENFORCE_INTERVAL"
 
 # Fully qualified domain name.
 BTENFORCE_DOMAIN="$BTENFORCE_DOMAIN"
@@ -609,22 +656,20 @@ EOF
     
     echo -e "${ORANGE}"
     cat "$BTENFORCE_CONFIG"
-    append_log "${GREEN}Configuration saved. Please review.\n${NC}"
-
     echo -e "${NC}"
 
     # Prompt whether to start from the beginning or exit.
     if read -s -k 1 -t 120 "FINAL_RESTART?Would you like to restart the configuration? (Y/[${ORANGE}N${NC}]): "; then
         if [[ "$FINAL_RESTART" == "Y" || "$FINAL_RESTART" == "y" ]]; then
-            append_log "\n${YELLOW}Restarting the configuration utility...${NC}"
+            append_log "\n${YELLOW}Restarting the configuration process...${NC}"
             sleep 2
             configure_btenforce
         else
-            append_log "\n${GREEN}Goodbye.${NC}"
+            append_log "\n${GREEN}Configuration complete. To make additional changes, re-run ${ORANGE}sudo btenforce -configure${NC}."
             exit 0
         fi
     else
-        append_log "\n${GREEN}Re-run the utility with btenforce -configure. Goodbye.${NC}"
+        append_log "\n${GREEN}Configuration complete. To make additional changes, re-run ${ORANGE}sudo btenforce -configure${NC}."
         exit 1
     fi
 }
@@ -679,6 +724,37 @@ prune_logs () {
     if [[ $? -ne 0 ]]; then
         return 1
     fi
+}
+
+set_btenforce_interval () {
+    if [[ -z "$BTENFORCE_INTERVAL" ]]; then
+        BTENFORCE_INTERVAL="5"
+    fi
+
+    # Get current interval
+    current_interval=$( plutil -extract "StartInterval" raw "$PLIST" 2>/dev/null )
+    
+    if [[ "$current_interval" == "$BTENFORCE_INTERVAL" ]]; then
+        return 0
+    fi
+
+    # Replace the interval.
+    plutil -replace StartInterval -integer "$BTENFORCE_INTERVAL" "$PLIST"
+    
+    # Fix permissions.
+    chown root:wheel "$PLIST"
+    chmod 644 "$PLIST"
+
+    # Validate the plist file.
+    plutil -lint "$PLIST"
+    if [[ $? -ne 0 ]]; then
+        append_log "Error: Could not validate the plist file."
+        return 1
+    fi
+
+    append_log "Set interval to ${BTENFORCE_INTERVAL}."
+
+    return 0
 }
 
 # Download and install the LaunchDaemon if it doesn't exist.
@@ -774,41 +850,108 @@ install_daemon () {
     fi
 }
 
-# Check whether Bluetooth is on or off.
-check_bluetooth () {
-    btutil="/usr/local/bin/blueutil"
+download_blueutil () {
+    
+    local blueutil_url="https://github.com/i-TechSupport-orlando/btenforce/raw/refs/heads/main/blueutil"
+    local temp_file="/tmp/blueutil.new"
+    local sha256
+    local sha256_local
 
-    # Source file if installed with the i-Tech package.
-    btutil_source="/usr/local/share/blueutil"
-        
-    # Double check that blueutil is executable.
-    if [[ ! -x "$btutil" ]]; then
-        if [[ -f "$btutil_source" ]]; then
-            cp "$btutil_source" "$btutil"
-            if [[ ! -f "$btutil" ]]; then
-                append_log "Could not find ${btutil}."
-                return 1
+    # Get expected sha256 checksum.
+    sha256=$( curl -fsSL "$blueutil_url" | shasum -a 256 | awk '{ print $1 }' )
+
+    if [[ -z "$sha256" ]] || [[ "${#sha256}" -ne 64 ]]; then
+        append_log "Error: Could not get sha256 checksum of blueutil. Output: ${sha256}"
+        return 1
+    fi
+
+    local max_attempts=3
+    local attempt=1
+
+    while [[ "$attempt" -le "$max_attempts" ]]; do
+        if curl -fsSL "$blueutil_url" -o "$temp_file"; then
+            sha256_local=$( shasum -a 256 "$temp_file" | awk '{ print $1 }' )
+
+            if [[ "$sha256_local" != "$sha256" ]]; then
+                append_log "Error: SHA256 checksum of downloaded blueutil does not match expected checksum."
+                rm -f "$temp_file"
             else
-                chmod +x "$btutil"
-                append_log "Copied Bluetooth utility from ${btutil_source} to ${btutil}. Version: $( /usr/local/bin/blueutil --version 2>/dev/null )"
+                if ! mv "$temp_file" "$BLUEUTIL"; then
+                    append_log "Error: Could not move blueutil to ${BLUEUTIL}."
+                    rm -f "$temp_file"
+                    return 1
+                fi
+
+                if ! chown root:wheel "$BLUEUTIL"; then
+                    append_log "Failed to change ownership of blueutil to root:wheel."
+                    return 1
+                fi
+
+                if ! chmod 644 "$BLUEUTIL"; then
+                    append_log "Failed to set permissions of blueutil to 644."
+                    return 1
+                fi
+
+                if ! chmod +x "$BLUEUTIL"; then
+                    append_log "Failed to set blueutil to executable."
+                    return 1
+                fi
+
+
+                return 0
             fi
         else
-            append_log "Error: Could not find Bluetooth utility source file at ${btutil_source}. Exiting without action."
-            return 1
+            append_log "Error: Could not download blueutil from GitHub on attempt ${attempt}. Retrying..."
         fi
+
+        sleep 2
+        (( attempt += 1 ))
+    done
+
+    append_log "Error: Could not download blueutil from GitHub after ${max_attempts} attempts."
+
+}
+
+# Check whether Bluetooth is on or off.
+check_bluetooth () {
+
+    local blue_util_src="/usr/local/share/blueutil"
+    
+    # Double check that blueutil is executable.
+    if [[ ! -x "$BLUEUTIL" ]]; then
+        if [[ -f "$blue_util_src" ]]; then
+            cp "$blue_util_src" "$BLUEUTIL"
+            if [[ ! -f "$BLUEUTIL" ]]; then
+                append_log "Could not find ${BLUEUTIL}."
+                if ! download_blueutil; then
+                    append_log "Failed to download blueutil. Exiting without action."
+                    return 1
+                else
+                    append_log "Downloaded blueutil from GitHub."
+                fi
+            fi
+        else
+            append_log "Error: Could not find Bluetooth utility source file at ${blue_util_src}. Attempting to download blueutil from GitHub."
+            if ! download_blueutil; then
+                append_log "Failed to download blueutil. Exiting without action."
+                return 1
+            fi
+        fi
+        chmod +x "$BLUEUTIL"
+        append_log "Copied Bluetooth utility from ${blue_util_src} to ${BLUEUTIL}."
     fi
 
     loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
-    uid=$( id -u "${loggedInUser}" 2>/dev/null ) || true
+    uid=$( id -u "$loggedInUser" 2>/dev/null ) || true
 
     # Required to run as root.
     export BLUEUTIL_ALLOW_ROOT=1
     
-    bstatus=$( launchctl asuser "$uid" sudo -u "$loggedInUser" /usr/local/bin/blueutil -p )
+    bstatus=$( launchctl asuser "$uid" sudo -u "$loggedInUser" "$BLUEUTIL" -p )
     
     # If Bluetooth is off, turn it back on.
     if [[ "$bstatus" -eq 0 ]]; then
-        launchctl asuser "$uid" sudo -u "$loggedInUser" /usr/local/bin/blueutil --power 1 2>/dev/null
+        launchctl asuser "$uid" sudo -u "$loggedInUser" "$BLUEUTIL" --power 1 2>/dev/null
         append_log "Reactivated Bluetooth. User: ${loggedInUser}"
     fi
 }
